// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frzzslmzakfzhvtdhzdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyenpzbG16YWtmemh2dGRoemR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTIxMzMsImV4cCI6MjA2ODkyODEzM30.dUrj8dGR7NIwtaG-Or08lj9V2Nyr-lrbiIgJZBEtkHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});