// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://hwgzyckwigaqticbphwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3Z3p5Y2t3aWdhcXRpY2JwaHduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTAxMTAsImV4cCI6MjA2NTU2NjExMH0.PAgPLz-p0Dy_zb6lJ-alcxR0LHUOA5fJ7SZI_7zwdtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);